#!/bin/bash

wget -O /projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/ray/tune/suggest/bayesopt.py https://raw.githubusercontent.com/thalvari/ray/ray-0.7.2-fixed/python/ray/tune/suggest/bayesopt.py
wget -O /projappl/project_2003107/anaconda3/envs/analytics-zoo/lib/python3.6/site-packages/zoo/automl/search/RayTuneSearchEngine.py https://raw.githubusercontent.com/thalvari/analytics-zoo/v0.8.1-fixed/pyzoo/zoo/automl/search/RayTuneSearchEngine.py
