#!/bin/bash

python run.py prophet_hpo train/nyc_taxi_stuck-at_level_0.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_1.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_2.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_3.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_4.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_5.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_0.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_1.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_2.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_3.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_4.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_5.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_0.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_1.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_2.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_3.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_4.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_5.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_0.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_1.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_2.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_3.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_4.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_5.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_0.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_1.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_2.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_3.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_4.csv 2064 timestamp value 120
python run.py prophet_hpo train/nyc_taxi_stuck-at_level_5.csv 2064 timestamp value 120
