#!/bin/bash

python run.py analytics-zoo train/temperature_multi_stuck-at_level_0.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_1.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_2.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_3.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_4.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_5.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_0.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_1.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_2.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_3.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_4.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_5.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_0.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_1.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_2.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_3.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_4.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_5.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_0.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_1.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_2.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_3.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_4.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_5.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_0.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_1.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_2.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_3.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_4.csv 2223 datetime Montreal 120
python run.py analytics-zoo train/temperature_multi_stuck-at_level_5.csv 2223 datetime Montreal 120
